// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyRyCcGlBHr8ZDAJEHQsCN0RAvRTU70QY',
    appId: '1:817558701544:ios:2d6ab4a74be9842f1b905d',
    messagingSenderId: '817558701544',
    projectId: 'smart-seed-recommender',
    storageBucket: 'smart-seed-recommender.firebasestorage.app',
    iosBundleId: 'com.example.seedRecommenderApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaFroJ8NioxXSy1dnNWT5qo3iI1C0e9U0',
    appId: '1:817558701544:web:f01d9751df7ecf171b905d',
    messagingSenderId: '817558701544',
    projectId: 'smart-seed-recommender',
    authDomain: 'smart-seed-recommender.firebaseapp.com',
    storageBucket: 'smart-seed-recommender.firebasestorage.app',
    measurementId: 'G-686DM3XZSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgxDBhKYgRqbjfKHRKcT1wHkzDiWQUMCw',
    appId: '1:817558701544:android:c6bbb61ad3c591fa1b905d',
    messagingSenderId: '817558701544',
    projectId: 'smart-seed-recommender',
    storageBucket: 'smart-seed-recommender.firebasestorage.app',
  );

}